-- Hospitalizations and ICU
-- 1 Row

-- Get state population
WITH CA_POPULATION as (
    select sum(POPULATION) as TOTAL_POPULATION
    from PRODUCTION.CDF_DEMOGRAPHICS_POPULATION_BY_COUNTY
    where YEAR = (select max(YEAR) from PRODUCTION.CDF_DEMOGRAPHICS_POPULATION_BY_COUNTY)
),
-- Get state-wide hospitalization counts by date
HOSPITALIZATIONS as (
    select REPORTING_FOR_DATE as REPORTING_FOR_DATE
      --,SUM(TOTAL_ADULT_PATIENTS_HOSPITALIZED_CONFIRMED_COVID) AS HOSPITALIZED_COVID_CONFIRMED_ADULTS
      --,SUM(TOTAL_PEDIATRIC_PATIENTS_HOSPITALIZED_CONFIRMED_COVID) AS HOSPITALIZED_COVID_CONFIRMED_PED
      ,SUM(TOTAL_ADULT_PATIENTS_HOSPITALIZED_CONFIRMED_COVID) + SUM(TOTAL_PEDIATRIC_PATIENTS_HOSPITALIZED_CONFIRMED_COVID) AS HOSPITALIZED_COVID_CONFIRMED_PATIENTS
      ,SUM(PREVIOUS_DAY_ADMISSION_ADULT_COVID_CONFIRMED) AS ADMITTED_COVID_CONFIRMED_ADULT
      ,SUM(PREVIOUS_DAY_ADMISSION_PEDIATRIC_COVID_CONFIRMED) AS ADMITTED_COVID_CONFIRMED_PED
      ,SUM(PREVIOUS_DAY_ADMISSION_ADULT_COVID_CONFIRMED) + SUM(PREVIOUS_DAY_ADMISSION_PEDIATRIC_COVID_CONFIRMED) AS ADMITTED_COVID_CONFIRMED_PATIENTS
      ,null AS HOSPITALIZED_SUSPECTED_COVID_PATIENTS
      ,SUM(STAFFED_ICU_ADULT_PATIENTS_CONFIRMED_COVID) + SUM(STAFFED_ICU_PEDIATRIC_PATIENTS_CONFIRMED_COVID) AS ICU_COVID_CONFIRMED_PATIENTS
      ,null AS ICU_SUSPECTED_COVID_PATIENTS
    FROM COVID.PRODUCTION.VW_NHSN_HOSPITALDATA_20230511
    group by REPORTING_FOR_DATE
),
-- Get state-wide aggregate calculations
TOTALS as (
    select
        SUM(ADMITTED_COVID_CONFIRMED_ADULT) + SUM(ADMITTED_COVID_CONFIRMED_PED) as TOTAL_ADMITTED_COVID_CONFIRMED_PATIENTS
    from HOSPITALIZATIONS
),
-- Do aggregate window calculations
CHANGES as (
    select REPORTING_FOR_DATE
        , HOSPITALIZED_COVID_CONFIRMED_PATIENTS
            , ZEROIFNULL(HOSPITALIZED_COVID_CONFIRMED_PATIENTS - LAG(HOSPITALIZED_COVID_CONFIRMED_PATIENTS,1,0) OVER (ORDER BY REPORTING_FOR_DATE)) AS HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILY
            , HOSPITALIZED_COVID_CONFIRMED_PATIENTS - LAG(HOSPITALIZED_COVID_CONFIRMED_PATIENTS,7,0) OVER (ORDER BY REPORTING_FOR_DATE) AS HOSPITALIZED_COVID_CONFIRMED_PATIENTS_LAST7DAYS
            , HOSPITALIZED_COVID_CONFIRMED_PATIENTS - LAG(HOSPITALIZED_COVID_CONFIRMED_PATIENTS,14,0) OVER (ORDER BY REPORTING_FOR_DATE) AS HOSPITALIZED_COVID_CONFIRMED_PATIENTS_LAST14DAYS
            , ROUND(AVG(HOSPITALIZED_COVID_CONFIRMED_PATIENTS) OVER (ORDER BY REPORTING_FOR_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)) as HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_AVG
            , SUM(HOSPITALIZED_COVID_CONFIRMED_PATIENTS) OVER (ORDER BY REPORTING_FOR_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
            , SUM(HOSPITALIZED_COVID_CONFIRMED_PATIENTS) OVER (ORDER BY REPORTING_FOR_DATE ROWS BETWEEN 13 PRECEDING AND 7 PRECEDING) as HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV
        , ADMITTED_COVID_CONFIRMED_PATIENTS
            , ZEROIFNULL(ADMITTED_COVID_CONFIRMED_PATIENTS - LAG(ADMITTED_COVID_CONFIRMED_PATIENTS,1,0) OVER (ORDER BY REPORTING_FOR_DATE)) AS ADMITTED_COVID_CONFIRMED_PATIENTS_DAILY
            , ADMITTED_COVID_CONFIRMED_PATIENTS - LAG(ADMITTED_COVID_CONFIRMED_PATIENTS,7,0) OVER (ORDER BY REPORTING_FOR_DATE) AS ADMITTED_COVID_CONFIRMED_PATIENTS_LAST7DAYS
            , ADMITTED_COVID_CONFIRMED_PATIENTS - LAG(ADMITTED_COVID_CONFIRMED_PATIENTS,14,0) OVER (ORDER BY REPORTING_FOR_DATE) AS ADMITTED_COVID_CONFIRMED_PATIENTS_LAST14DAYS
            , ROUND(AVG(ADMITTED_COVID_CONFIRMED_PATIENTS) OVER (ORDER BY REPORTING_FOR_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)) as ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_AVG
            , SUM(ADMITTED_COVID_CONFIRMED_PATIENTS) OVER (ORDER BY REPORTING_FOR_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
            , SUM(ADMITTED_COVID_CONFIRMED_PATIENTS) OVER (ORDER BY REPORTING_FOR_DATE ROWS BETWEEN 13 PRECEDING AND 7 PRECEDING) as ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV
        , HOSPITALIZED_SUSPECTED_COVID_PATIENTS
            , ZEROIFNULL(HOSPITALIZED_SUSPECTED_COVID_PATIENTS - LAG(HOSPITALIZED_SUSPECTED_COVID_PATIENTS,1,0) OVER (ORDER BY REPORTING_FOR_DATE)) AS HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILY
            , HOSPITALIZED_SUSPECTED_COVID_PATIENTS - LAG(HOSPITALIZED_SUSPECTED_COVID_PATIENTS,7,0) OVER (ORDER BY REPORTING_FOR_DATE) AS HOSPITALIZED_SUSPECTED_COVID_PATIENTS_LAST7DAYS
            , HOSPITALIZED_SUSPECTED_COVID_PATIENTS - LAG(HOSPITALIZED_SUSPECTED_COVID_PATIENTS,14,0) OVER (ORDER BY REPORTING_FOR_DATE) AS HOSPITALIZED_SUSPECTED_COVID_PATIENTS_LAST14DAYS
        , ICU_COVID_CONFIRMED_PATIENTS
            , ZEROIFNULL(ICU_COVID_CONFIRMED_PATIENTS - LAG(ICU_COVID_CONFIRMED_PATIENTS,1,0) OVER (ORDER BY REPORTING_FOR_DATE)) AS ICU_COVID_CONFIRMED_PATIENTS_DAILY
            , ICU_COVID_CONFIRMED_PATIENTS - LAG(ICU_COVID_CONFIRMED_PATIENTS,7,0) OVER (ORDER BY REPORTING_FOR_DATE) AS ICU_COVID_CONFIRMED_PATIENTS_LAST7DAYS
            , ICU_COVID_CONFIRMED_PATIENTS - LAG(ICU_COVID_CONFIRMED_PATIENTS,14,0) OVER (ORDER BY REPORTING_FOR_DATE) AS ICU_COVID_CONFIRMED_PATIENTS_LAST14DAYS
            , SUM(ICU_COVID_CONFIRMED_PATIENTS) OVER (ORDER BY REPORTING_FOR_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
            , SUM(ICU_COVID_CONFIRMED_PATIENTS) OVER (ORDER BY REPORTING_FOR_DATE ROWS BETWEEN 13 PRECEDING AND 7 PRECEDING) as ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV
        , ICU_SUSPECTED_COVID_PATIENTS
            , ZEROIFNULL(ICU_SUSPECTED_COVID_PATIENTS - LAG(ICU_SUSPECTED_COVID_PATIENTS,1,0) OVER (ORDER BY REPORTING_FOR_DATE)) AS ICU_SUSPECTED_COVID_PATIENTS_DAILY
            , ICU_SUSPECTED_COVID_PATIENTS - LAG(ICU_SUSPECTED_COVID_PATIENTS,7,0) OVER (ORDER BY REPORTING_FOR_DATE) AS ICU_SUSPECTED_COVID_PATIENTS_LAST7DAYS
            , ICU_SUSPECTED_COVID_PATIENTS - LAG(ICU_SUSPECTED_COVID_PATIENTS,14,0) OVER (ORDER BY REPORTING_FOR_DATE) AS ICU_SUSPECTED_COVID_PATIENTS_LAST14DAYS
    FROM HOSPITALIZATIONS
    WHERE REPORTING_FOR_DATE IS NOT NULL
),
-- Calculate percentage changes
OUTPUT_DATA as (
select TOP 1 REPORTING_FOR_DATE
    , HOSPITALIZED_COVID_CONFIRMED_PATIENTS
        , HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILY
        , CASE HOSPITALIZED_COVID_CONFIRMED_PATIENTS
            WHEN 0 THEN 0
            WHEN HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILY THEN 1
            ELSE HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILY / (HOSPITALIZED_COVID_CONFIRMED_PATIENTS-HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILY)
        END AS HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILYPCTCHG
        , HOSPITALIZED_COVID_CONFIRMED_PATIENTS_LAST7DAYS
        , HOSPITALIZED_COVID_CONFIRMED_PATIENTS_LAST14DAYS
        , HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_AVG
        , HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
        , HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL - HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV as HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE
        , ZEROIFNULL(HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE / NULLIFZERO(HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV)) AS HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE_FACTOR

    , ADMITTED_COVID_CONFIRMED_PATIENTS
        , ADMITTED_COVID_CONFIRMED_PATIENTS_DAILY
        , CASE ADMITTED_COVID_CONFIRMED_PATIENTS
            WHEN 0 THEN 0
            WHEN ADMITTED_COVID_CONFIRMED_PATIENTS_DAILY THEN 1
            ELSE ADMITTED_COVID_CONFIRMED_PATIENTS_DAILY / (ADMITTED_COVID_CONFIRMED_PATIENTS-ADMITTED_COVID_CONFIRMED_PATIENTS_DAILY)
        END AS ADMITTED_COVID_CONFIRMED_PATIENTS_DAILYPCTCHG
        , ADMITTED_COVID_CONFIRMED_PATIENTS_LAST7DAYS
        , ADMITTED_COVID_CONFIRMED_PATIENTS_LAST14DAYS
        , ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_AVG
        , ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
        , ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL - ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV as ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE
        , ZEROIFNULL(ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE / NULLIFZERO(ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV)) AS ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE_FACTOR

    , HOSPITALIZED_SUSPECTED_COVID_PATIENTS
        , HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILY
        , CASE HOSPITALIZED_SUSPECTED_COVID_PATIENTS
            WHEN 0 THEN 0
            WHEN HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILY THEN 1
            ELSE HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILY / (HOSPITALIZED_SUSPECTED_COVID_PATIENTS-HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILY)
        END AS HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILYPCTCHG
        , HOSPITALIZED_SUSPECTED_COVID_PATIENTS_LAST7DAYS
        , HOSPITALIZED_SUSPECTED_COVID_PATIENTS_LAST14DAYS
    , ICU_COVID_CONFIRMED_PATIENTS
        , ICU_COVID_CONFIRMED_PATIENTS_DAILY
        , CASE ICU_COVID_CONFIRMED_PATIENTS
            WHEN 0 THEN 0
            WHEN ICU_COVID_CONFIRMED_PATIENTS_DAILY THEN 1
            ELSE ICU_COVID_CONFIRMED_PATIENTS_DAILY / (ICU_COVID_CONFIRMED_PATIENTS-ICU_COVID_CONFIRMED_PATIENTS_DAILY)
        END AS ICU_COVID_CONFIRMED_PATIENTS_DAILYPCTCHG
        , ICU_COVID_CONFIRMED_PATIENTS_LAST7DAYS
        , ICU_COVID_CONFIRMED_PATIENTS_LAST14DAYS
        , ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
        , ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL - ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV as ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE
        , ZEROIFNULL(ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE / NULLIFZERO(ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_PREV)) AS ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE_FACTOR

    , ICU_SUSPECTED_COVID_PATIENTS
        , ICU_SUSPECTED_COVID_PATIENTS_DAILY
        , CASE ICU_SUSPECTED_COVID_PATIENTS
            WHEN 0 THEN 0
            WHEN ICU_SUSPECTED_COVID_PATIENTS_DAILY THEN 1
            ELSE ICU_SUSPECTED_COVID_PATIENTS_DAILY / (ICU_SUSPECTED_COVID_PATIENTS-ICU_SUSPECTED_COVID_PATIENTS_DAILY)
        END AS ICU_SUSPECTED_COVID_PATIENTS_DAILYPCTCHG
        , ICU_SUSPECTED_COVID_PATIENTS_LAST7DAYS
        , ICU_SUSPECTED_COVID_PATIENTS_LAST14DAYS
    , TOTAL_ADMITTED_COVID_CONFIRMED_PATIENTS
from CHANGES CROSS JOIN TOTALS
ORDER BY REPORTING_FOR_DATE DESC
)
select
    REPORTING_FOR_DATE
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILY
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILYPCTCHG
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS_LAST7DAYS
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS_LAST14DAYS
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_AVG
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE_FACTOR
    ,HOSPITALIZED_COVID_CONFIRMED_PATIENTS / (TOTAL_POPULATION/100000) AS HOSPITALIZED_COVID_CONFIRMED_PATIENTS_PER_100K
    ,ADMITTED_COVID_CONFIRMED_PATIENTS
    ,ADMITTED_COVID_CONFIRMED_PATIENTS_DAILY
    ,ADMITTED_COVID_CONFIRMED_PATIENTS_DAILYPCTCHG
    ,ADMITTED_COVID_CONFIRMED_PATIENTS_LAST7DAYS
    ,ADMITTED_COVID_CONFIRMED_PATIENTS_LAST14DAYS
    ,ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_AVG
    ,ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
    ,ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE
    ,ADMITTED_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE_FACTOR
    ,ADMITTED_COVID_CONFIRMED_PATIENTS / (TOTAL_POPULATION/100000) AS ADMITTED_COVID_CONFIRMED_PATIENTS_PER_100K
    ,zeroifnull(HOSPITALIZED_SUSPECTED_COVID_PATIENTS) as HOSPITALIZED_SUSPECTED_COVID_PATIENTS
    ,zeroifnull(HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILY) as HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILY
    ,zeroifnull(HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILYPCTCHG) as HOSPITALIZED_SUSPECTED_COVID_PATIENTS_DAILYPCTCHG
    ,zeroifnull(HOSPITALIZED_SUSPECTED_COVID_PATIENTS_LAST7DAYS) as HOSPITALIZED_SUSPECTED_COVID_PATIENTS_LAST7DAYS
    ,zeroifnull(HOSPITALIZED_SUSPECTED_COVID_PATIENTS_LAST14DAYS) as HOSPITALIZED_SUSPECTED_COVID_PATIENTS_LAST14DAYS
    ,ICU_COVID_CONFIRMED_PATIENTS
    ,ICU_COVID_CONFIRMED_PATIENTS_DAILY
    ,ICU_COVID_CONFIRMED_PATIENTS_DAILYPCTCHG
    ,ICU_COVID_CONFIRMED_PATIENTS_LAST7DAYS
    ,ICU_COVID_CONFIRMED_PATIENTS_LAST14DAYS
    ,ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL
    ,ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE
    ,ICU_COVID_CONFIRMED_PATIENTS_7_DAY_TOTAL_CHANGE_FACTOR
    ,zeroifnull(ICU_SUSPECTED_COVID_PATIENTS) as ICU_SUSPECTED_COVID_PATIENTS
    ,zeroifnull(ICU_SUSPECTED_COVID_PATIENTS_DAILY) as ICU_SUSPECTED_COVID_PATIENTS_DAILY
    ,zeroifnull(ICU_SUSPECTED_COVID_PATIENTS_DAILYPCTCHG) as ICU_SUSPECTED_COVID_PATIENTS_DAILYPCTCHG
    ,zeroifnull(ICU_SUSPECTED_COVID_PATIENTS_LAST7DAYS) as ICU_SUSPECTED_COVID_PATIENTS_LAST7DAYS
    ,zeroifnull(ICU_SUSPECTED_COVID_PATIENTS_LAST14DAYS) as ICU_SUSPECTED_COVID_PATIENTS_LAST14DAYS
    ,TOTAL_ADMITTED_COVID_CONFIRMED_PATIENTS
    ,TOTAL_POPULATION

from OUTPUT_DATA CROSS JOIN CA_POPULATION
